name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dokku deploy
      uses: rikw22/dokku-github-action@v6.2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_TCC }}
        HOST: ec2-18-230-118-199.sa-east-1.compute.amazonaws.com
        PROJECT: web.laravel.1
        FORCE_DEPLOY: true
