name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dokku deploy
      uses: ra-20017322-5/dokku-github-action@v6.2
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ec2-15-229-252-12.sa-east-1.compute.amazonaws.com
        PROJECT: web.laravel
        FORCE_DEPLOY: true
